### ISSUE TITLE
[BUG] - Error Msg: There was no registered handler for "TextboxEntry"

### ISSUE THREAD

**Issue by rahulcs1988** [EpicGames/PixelStreamingInfrastructure-archived-2024#346]
**Frontend Version: **
E.g. UE5.2

lib-pixelstreamingfrontend.esm.js:3370 Level: Error
Msg: There was no registered handler for "TextboxEntry" - try adding one using registerMessageHandler(MessageDirection.ToStreamer, "TextboxEntry", myHandler)
Caller: 
    at Logger.GetStackTrace (http://localhost/player.js:3550:23)
    at http://localhost/player.js:7015:139
    at Array.forEach (<anonymous>)
    at WebRtcPlayerController.onProtocolMessage (http://localhost/player.js:6991:39)
    at http://localhost/player.js:6921:191
    at WebRtcPlayerController.handleOnMessage (http://localhost/player.js:6892:75)
    at sendrecvDataChannelController.handleOnMessage (http://localhost/player.js:7508:75)
    at dataChannel.onmessage (http://localhost/player.js:1293:51)

Any idea for fixing this issue?

**Comment by zixixr** [comment]
I also encountered it, and I think this is indeed a bug, and as far as I know, it's been fixed in 5.3. What I did was creating a handler for this TextboxEntry to avoid this ERROR.

**Comment by Belchy06** [comment]
Hey @rahulcs1988,

This issue has been fixed as of: https://github.com/EpicGames/PixelStreamingInfrastructure/commit/1373f41257c718b8b3273e868db008374d490c28

Cheers
